2.0.2
[[21 70 63]
 [71 50 80]
 [83 86 63]
 [57 10 18]]


In [3]:
np.random.seed(50)
c = np.random.randint(10,100,(4,3))
print(c)

[[58 21 43]
 [14 80 80]
 [32 15 12]
 [81 78 88]]


In [4]:
np.ravel(c)

array([58, 21, 43, 14, 80, 80, 32, 15, 12, 81, 78, 88])

In [12]:
np.ravel(c,order='F')


array([58, 14, 32, 81, 21, 80, 15, 78, 43, 80, 12, 88])

In [15]:
np.ravel(c,order='C')

array([58, 21, 43, 14, 80, 80, 32, 15, 12, 81, 78, 88])

In [19]:
c.T

array([[58, 14, 32, 81],
       [21, 80, 15, 78],
       [43, 80, 12, 88]])

In [ ]:
"""1.list,2.numpy,3.tenser"""

In [23]:
# Operation in Numpy Array
a = np.array([10,20,30])
b = np.array([10,20,30])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a**b)
print(a%b)


[20 40 60]
[0 0 0]
[100 400 900]
[1. 1. 1.]
[1 1 1]
[         10000000000 -2101438300051996672  2565992168703393792]
[0 0 0]


In [25]:
c = np.array([1,2,3,4])
d = np.array([2,2,2,2])

print(c==d)
print(c!=d)
print(c<d)
print(c>d)
print(c>=d)
print(c>=d)

[False  True False False]
[ True False  True  True]
[ True False False False]
[False False  True  True]
[False  True  True  True]
[False  True  True  True]


In [27]:
e = np.array([True, False, True])
f = np.array([True, True, False])

print(np.logical_and(e,f))
print(np.logical_or(e,f))
print(np.logical_not(e))

[ True False False]
[ True  True  True]
[False  True False]


In [33]:
# Mathematical Operations
a = np.array([4,9,16])
b = np.array([4,9,1])

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.power(a,b))
print(np.mod(a,b))
print(np.sqrt(a))
print(np.exp(a))
print(np.log(a))
print(np.log10(a))

[ 8 18 17]
[ 0  0 15]
[16 81 16]
[ 1.  1. 16.]
[      256 387420489        16]
[0 0 0]
[2. 3. 4.]
[5.45981500e+01 8.10308393e+03 8.88611052e+06]
[1.38629436 2.19722458 2.77258872]
[0.60205999 0.95424251 1.20411998]
