In [2]:
import numpy as np 
arr = np.array([9.234, 6.567, 3.891])

print(np.round(arr,1))
print(np.floor(arr))
print(np.ceil(arr))

[9.2 6.6 3.9]
[9. 6. 3.]
[10.  7.  4.]


In [3]:
arr

array([9.234, 6.567, 3.891])

In [4]:
np.median(arr)


np.float64(6.567)

In [5]:
np.prod(arr)

np.float64(235.948987098)

In [6]:
np.cumsum(arr)

array([ 9.234, 15.801, 19.692])

In [7]:
np.percentile(arr,90)

np.float64(8.7006)

In [8]:
x = np.array([10,20,20,30,2020,2020,202,2020])
x[::-1]

array([2020,  202, 2020, 2020,   30,   20,   20,   10])

In [9]:
x[:5:]

array([  10,   20,   20,   30, 2020])

In [10]:
x[2:5:]

array([  20,   30, 2020])

In [11]:
x[-5::2]

array([  30, 2020, 2020])

In [12]:
y = np.random.randint(10,100,12,).reshape(3,4)
print(y)

[[63 14 89 83]
 [53 41 42 44]
 [26 52 57 49]]


In [13]:
y[::]

array([[63, 14, 89, 83],
       [53, 41, 42, 44],
       [26, 52, 57, 49]])

In [14]:
y[::2,1::2]

array([[14, 83],
       [52, 49]])

In [15]:
y[1::,::3]

array([[53, 44],
       [26, 49]])

In [16]:
y[-1::]

array([[26, 52, 57, 49]])

In [17]:
y = np.random.randint(10,100,27).reshape(3,3,3)
print(y)

[[[40 58 19]
  [30 35 83]
  [81 14 63]]

 [[53 24 79]
  [96 52 87]
  [95 65 43]]

 [[83 84 95]
  [10 13 42]
  [34 82 76]]]


In [18]:
y[layer:row:column]

NameError: name 'layer' is not defined

In [ ]:
"""https://colab.research.google.com/drive/1txdHwzQy4vsJ_n6h7lwluRUu3hmFfTFV?usp=sharing#scrollTo=_wapW622Vf1t"""


In [20]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.concatenate((a,b)))
print(np.hstack((a,b)))
print(np.vstack((a,b)))


[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [21]:
arr = np.arange(9)
print(np.split(arr,3))

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [24]:
arr = np.array([1,2,3,4])
print(np.insert(arr,2,10))
print(np.append(arr,10))
print(np.delete(arr,2))

[ 1  2 10  3  4]
[ 1  2  3  4 10]
[1 2 4]


In [25]:
arr = np.array([1,2,2,3,3,3,4])
print(np.unique(arr))

[1 2 3 4]


In [26]:
arr = np.array([3,1,4,1,5,9])
print(np.sort(arr))
print(np.argsort(arr))

[1 1 3 4 5 9]
[1 3 0 2 4 5]


In [28]:
arr = np.array([0,1,2,0])
print(np.nonzero(arr))

(array([1, 2]),)


In [30]:
arr = np.array([0,1,2,0,2,3,0])
print(list(np.nonzero(arr)))

[array([1, 2, 4, 5])]


In [32]:
arr = np.random.randint(10,100,9).reshape(3,3)
print(arr)

[[67 16 43]
 [52 32 69]
 [59 70 82]]


In [33]:
np.clip(arr,30,75)

array([[67, 30, 43],
       [52, 32, 69],
       [59, 70, 75]])

In [ ]:
arr = np.array([1,2,np.nan,4,5])
arr[np.isnan(arr)] = 3
arr


array([1., 2., 3., 4., 5.])

In [41]:
np.random.seed(42)
arr = np.random.randint(10,100,9).reshape(3,3)
arr

array([[61, 24, 81],
       [70, 30, 92],
       [96, 84, 84]])

In [43]:
np.sum(arr,axis=0)

array([227, 138, 257])

In [44]:
np.sum(arr,axis=1)

array([166, 192, 264])

In [45]:
np.mean(arr,axis=0)

array([75.66666667, 46.        , 85.66666667])

In [49]:
np.diagonal(arr,offset=2)

array([81])

In [50]:
np.trace(arr)

np.int64(175)

In [51]:
np.diag([10,20,30,40])

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 40]])