In [1]:
import numpy as np
m = np.linspace(1,10,5)
print(m,type(m))

[ 1.    3.25  5.5   7.75 10.  ] <class 'numpy.ndarray'>


In [2]:
# Arithmetic Progression
"""
l = a+(n-1)d
10-1 = 4d
d = 9/4 = 2.25
"""

'\nl = a+(n-1)d\n10-1 = 4d\nd = 9/4 = 2.25\n'

In [3]:
print(np.logspace(0,3,4))   

[   1.   10.  100. 1000.]


In [4]:
print(np.full((3,4),5,dtype=int))

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [5]:
print(np.zeros((3,4),dtype=int))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [6]:
print(np.ones((3,4),dtype=int))

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [7]:
from numpy import dtype

print(np.eye(3,dtype=int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [8]:
d = np.identity(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
d = np.array([[1,2,3],
            [3,4,5],
            [4,5,6]])
print(d)

[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [10]:
import numpy as np
print(np.__version__)


n = np.random.randint(10,100,12).reshape(4,3)
print(n)

2.1.3
[[82 37 95]
 [93 65 33]
 [17 76 51]
 [78 22 45]]
