In [23]:
import numpy as np 
hospital = np.array([
    [   #Floor 1
        ["Room1", "Room2"],
        ["Room3", "Room4"]
    ],
    [   # Floor 2
        ["Room5", "Room6"],
        ["Room7", "Room8"]
    ],
    [   # Floor 3
        ["Room5", "Room6"],
        ["Room7", "Room8"]
    ]
])

print("number of dimensions:",hospital.ndim)
print("size:", hospital.size)
print("shape:",hospital.shape)
# List style indexing
print(hospital[1][0][0])
# NumPy standard style (Recommended)
print(hospital[0, 0, 0])



number of dimensions: 3
size: 12
shape: (3, 2, 2)
Room5
Room1


In [24]:


zeros_array = np.zeros((2,3))
print("Zeros Array:")
print(zeros_array)

Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]]


In [25]:
zeros_array = np.ones((2,3))
print("Zeros Array:")
print(zeros_array)

Zeros Array:
[[1. 1. 1.]
 [1. 1. 1.]]


In [26]:
range_array = np.arange(1,101)
print("Zeros Array:")
print(range_array)

Zeros Array:
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [27]:
import numpy as np
arry1 = np.array ([4,6,2,4])
arry2 = np.array ([2,2,2,4])

print("Addition:", arry1+arry2)
print("Subtraction:", arry1-arry2)
print("Multiplication:", arry1*arry2)
print("Dvision:", arry1 / arry2)

Addition: [6 8 4 8]
Subtraction: [2 4 0 0]
Multiplication: [ 8 12  4 16]
Dvision: [2. 3. 1. 1.]


In [28]:
import numpy as np
arry1 = np.array([4, 6, 2, 4])
arry2 = np.array([2, 2, 2, 4])

# User se operator input karwaye (jaise: +, -, *, ya /)
b = input("Enter operator (+, -, *, /): ")

if b == "+":
    A = arry1 + arry2
elif b == "-":
    A = arry1 - arry2
elif b == "*":
    A = arry1 * arry2
elif b == "/":
    A = arry1 / arry2
else:
    A = "Invalid Operator!"

print(A)


[6 8 4 8]


In [29]:
b = input("Enter operator (+, -, *, /): ") # Maan lijiye user ne '/' daala
A = eval(f"arry1 {b} arry2") # Yeh background mein run karega: arry1 / arry2
print(A)


[6 8 4 8]


In [30]:
b = input("Enter here denominator (number): ")
# input() हमेशा string देता है, इसलिए इसे float या int में बदलना जरूरी है
denominator = float(b)

A = arry1 / denominator
print(A)


[0.5  0.75 0.25 0.5 ]


In [31]:
"""
Problem 1: Create a NumPy array containing 
numbers from 1 to 20.
"""
#Problem 1
arr_p1 = np.arange(1,21)
print("Problem 1:", arr_p1)


Problem 1: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [32]:
"""
Problem 2: Create a 3x3 metrix with value from 1 to 9.
"""
arry_p2 = np.arange(1,10).reshape(3,3)
print("Problem 2:")
print(arry_p2)

Problem 2:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
"""
Problem 3: Multiply every element of an array by 10.
"""
# Problem 3
arry_p3 = np.array([2,3,4])
print("Problem 3:", arry_p3*10)

Problem 3: [20 30 40]


In [40]:
"""
Problem 4: Find the shape and dimension of a 4x5 zero matrix.
"""
arr_p4 = np.zeros((4,5))
print("Problem 4 Shape:")
print(arr_p4)
print("Problem 4 Shape:",arr_p4.shape)
print("Problem 4 Dimension:",arr_p4.ndim)


Problem 4 Shape:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Problem 4 Shape: (4, 5)
Problem 4 Dimension: 2


In [35]:
#linspace 