In [10]:
import numpy as np

arr = np.linspace(1, 20, 5)
print(arr)

[ 1.    5.75 10.5  15.25 20.  ]


In [11]:
arr = np.empty((3,3))
print(arr)

[[ 5.17547039e-31 -1.03509408e-30  2.58773519e-31]
 [-1.03509408e-30  2.25132962e-30 -6.98688502e-31]
 [ 2.58773519e-31 -6.98688502e-31  4.01098955e-31]]


In [ ]:

# print(np.identity(4))
a = np.identity(10)
print(a)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [27]:
print(np.eye(2,4))
b = 3.14*a
c = b*2
print(b)
print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]]
[[3.14 0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   3.14 0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   3.14 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   3.14 0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   3.14 0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   3.14 0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   3.14 0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   3.14 0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   3.14 0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   3.14]]
[[6.28 0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   6.28 0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   6.28 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   6.28 0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   6.28 0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   6.28 0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   6.28 0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   6.28 0.   0.  ]
 [0.   0.   0.

In [75]:
np.random.seed(42)
print("Uniform:", np.random.rand(3,3))
print("Normal:", np.random.randn(1,5))
print("Random Integers:", np.random.randint(2,4))
print("Random Choice:", np.random.choice(2,10))


Uniform: [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
Normal: [[-0.58087813 -0.52516981 -0.57138017 -0.92408284 -2.61254901]]
Random Integers: 2
Random Choice: [0 0 0 1 1 1 1 1 0 1]
