In [19]:
import numpy as np
matrix = np.array([[1,2,3],[4,5,6]])

print("Original:\n", matrix)
print("Transpose using T:\n", matrix.T)
print("Transpose using function:\n", np.transpose(matrix))

Original:
 [[1 2 3]
 [4 5 6]]
Transpose using T:
 [[1 4]
 [2 5]
 [3 6]]
Transpose using function:
 [[1 4]
 [2 5]
 [3 6]]


In [20]:
"""flore and sealing"""
"""add or less in"""

'add or less in'