In [ ]:
"""
Numpy_3: Solve que
"""


In [25]:
"""
1. Create an array from 1 to 15.
Split it into 5 equal parts.
"""
import numpy as np 
arry1 = np.arange(1,16)
split5 = np.split(arry1, 5)

print("Original Array:", arry1)
print("Split Parts:\n",split5)

Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Split Parts:
 [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12]), array([13, 14, 15])]


In [23]:
"""
1. Create an array from 1 to 15.
Split it into 5 equal parts.
""" #AI
import numpy as np 

# 1 se 15 tak ka array banana
arry1 = np.arange(1, 16)

# 5 equal parts mein split karna
parts = np.split(arry1, 5)

print("Original Array:", arry1)
print("Split Parts:")
for part in parts:
    print(part)


Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Split Parts:
[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]
[13 14 15]
